In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

df_dep = pd.DataFrame(pd.read_csv("./clasificar_depresion.csv"))

In [2]:
df_dep

,Unnamed: 0,Tipo,Melancolía,Edad,MADRS1,MADRS2,Hosp,Dia,Hora5,Hora6,Hora7,Hora8,Hora9,Hora10,Hora11,Hora12,Hora13,Hora14,Hora15
0,0,1,1,37,19,19,1,164.070516,209.850000,129.116667,60.466667,99.950000,41.533333,32.450000,148.733333,8.000000,4.083333,7.066667,4.033333
1,1,1,1,37,19,19,1,110.545196,12.650000,4.516667,6.433333,5.666667,36.550000,161.816667,228.833333,432.483333,192.400000,38.350000,7.733333
2,2,1,1,37,19,19,1,130.902982,184.883333,206.700000,192.216667,447.583333,157.016667,60.083333,47.666667,79.966667,85.483333,2.766667,0.916667
3,3,1,1,37,19,19,1,226.821107,12.450000,5.250000,9.816667,9.683333,9.683333,9.866667,16.900000,144.566667,317.800000,368.250000,367.700000
4,4,1,1,37,19,19,1,159.088027,119.783333,170.333333,80.250000,284.633333,230.133333,325.300000,42.450000,86.900000,66.050000,132.216667,9.900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,286,1,1,32,29,23,0,349.058435,494.600000,757.466667,520.700000,404.833333,509.550000,230.466667,112.066667,384.566667,67.766667,6.650000,9.683333
287,287,1,1,32,29,23,0,130.404472,11.383333,45.000000,5.083333,15.183333,1.333333,14.950000,33.000000,11.800000,294.866667,225.800000,270.050000
288,288,1,1,32,29,23,0,1.012703,0.000000,0.000000,2.150000,3.716667,3.466667,0.000000,0.000000,0.133333,12.933333,1.550000,0.050000
289,289,1,1,32,29,23,0,0.549797,0.000000,0.000000,1.200000,0.566667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
290,290,1,1,32,29,23,0,4.233079,0.000000,0.000000,0.000000,0.550000,0.000000,4.100000,0.333333,0.000000,0.000000,0.000000,3.850000

In [15]:
from sklearn.model_selection import train_test_split
import time
train, test = train_test_split(df_dep, test_size = 0.30)

variables_train = train[['Hora5','Hora6','Hora7','Hora8','Hora9','Hora10','Hora11','Hora12','Hora13','Hora14','Hora15']].to_numpy() 
variables_test = test[['Hora5','Hora6','Hora7','Hora8','Hora9','Hora10','Hora11','Hora12','Hora13','Hora14','Hora15']].to_numpy()

tipo_train = train['Tipo'].to_numpy()
tipo_test = test['Tipo'].to_numpy()

In [17]:
#REGRESIÓN LOGÍSTICA
from sklearn.datasets import load_iris 
from sklearn.linear_model import LogisticRegression 
inicio_RL = time.time()
reg_log = LogisticRegression(random_state=0, max_iter=10000).fit(variables_train, tipo_train) 
fin_RL = time.time()
t_RL = fin_RL - inicio_RL 
print("El modelo de Regresión Logística tarda en procesarse",t_RL, "segundos.")
print("Se predicen un", reg_log.score(variables_train, tipo_train) * 100, "% de los casos con Regresión Logística.")


#REDES NEURONALES
from sklearn.neural_network import MLPClassifier
inicio_RN = time.time()
redes = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(15, 25), random_state=1).fit(variables_train,tipo_train)
fin_RN = time.time()
t_RN = fin_RN - inicio_RN 
print("El modelo de Redes Neuronales tarda en procesarse",t_RN, "segundos.")
print("Se predicen un",redes.score(variables_train,tipo_train)* 100, "% de los casos con Redes Neuronales.")


#KERAS
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers.core import Dense

RL_Keras = Sequential()
RL_Keras.add(Dense(units=64, activation = 'relu'))
RL_Keras.add(Dense(units=32, activation = 'ELU'))
RL_Keras.add(Dense(units=16, activation = 'ELU'))
RL_Keras.add(Dense(units=1, activation = 'sigmoid'))
RL_Keras.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

inicio_Keras = time.time()

RL_Keras.fit(x=variables_train, y=tipo_train, verbose=0, epochs=80)

fin_Keras = time.time()
t_Keras = fin_Keras - inicio_Keras 
print("El modelo de Keras tarda en procesarse",t_Keras, "segundos.")
print("Se predicen un",RL_Keras.evaluate(variables_train,tipo_train)[1]* 100, "% de los casos con Keras.")

El modelo de Regresión Logística tarda en procesarse 0.015136957168579102 segundos.
Se predicen un 70.44334975369459 % de los casos con Regresión Logística.
El modelo de Redes Neuronales tarda en procesarse 0.17351269721984863 segundos.
Se predicen un 93.59605911330048 % de los casos con Redes Neuronales.

C:\Users\anaji\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

El modelo de Keras tarda en procesarse 4.481487512588501 segundos.
7/7 [==============================] - 0s 3ms/step - loss: 0.0361 - accuracy: 1.0000
Se predicen un 100.0 % de los casos con Keras.